services:
  subconverter:
    image: asdlokj1qpi23/subconverter:0.9.9
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:25500"
    volumes:
      - ./data:/mnt
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
